name: Testing
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: tsc --noEmit && bun install --frozen-lockfile
